version: '3'

services:
  soda-go:
    build:
      context: ./soda-go
    ports:
      - "8080:8080"
    depends_on:
      soda-rabbitmq:
        condition: service_started
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080"]
        interval: 30s
        timeout: 10s
        retries: 5
    restart: always


  soda-ffmpeg-go:
    build:
      context: ./soda-ffmpeg-go
    ports:
      - "8082:8082"
    depends_on:
      soda-rabbitmq:
        condition: service_started
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082"]
        interval: 30s
        timeout: 10s
        retries: 5
    restart: always

  soda-nginx:
    build:
      context: ./soda-nginx
    ports:
      - "80:80"
    depends_on:
      soda-rabbitmq:
        condition: service_started
      soda-go:
        condition: service_started
      soda-ffmpeg-go:
        condition: service_started
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
    restart: always

  soda-rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5