# Use the official Golang image
FROM golang:latest

ENV RABBITMQ_URL=amqp://guest:guest@soda-rabbitmq/

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go application source code to the container
COPY . .

RUN go mod download

# Build the Go application
RUN go build -o soda-ffmpeg-go

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Command to run the Go application
CMD ["./soda-ffmpeg-go"]
