# Use the official Golang image
FROM golang:latest

# Set environment variables
ENV ENV=release \
    RABBITMQ_URL=amqp://guest:guest@soda-rabbitmq/

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go application source code to the container
COPY . .

RUN go mod download

# Build the Go application
RUN go build -o soda-go

# Command to run the Go application
CMD ["./soda-go"]
